name: Deploy to production
on:
  push:
    tags:
      - 'v1.*'

jobs:
  install-test-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1

      - name: 'Install Nodejs'
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: 'Install packages'
        run: npm install

      - name: 'Run unit tests'
        run: npm run test:u

      - name: 'Run e2e cypress tests'
        uses: cypress-io/github-action@v1
        with:
          browser: chrome
          config-file: tests/e2e/cypress.json
          start: npm run dev
          wait-on: 'http://localhost:3000/'
          parallel: true
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: 'Build the dist'
        run: npm run build

      - name: 'Setup gcloud'
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '271.0.0'
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: 'Deploy the app'
        run: gcloud app deploy --project=${{ secrets.CLOUDSDK_CORE_PROJECT }}
